- name: Service
  hosts: myhosts
  become: yes
  tasks:
    - name: Copy and start system-service
      copy:
        src: ../system-service/flask-app.service
        dest: /etc/systemd/system/
      notify:
        - reload systemd
        - enable flask-app
        - start flask-app
  handlers:
      - name: reload systemd
        systemd:
          daemon_reload: yes

      - name: enable flask-app
        systemd:
            name: flask-app.service
            enabled: yes

      - name: start flask-app
        systemd:
            name: flask-app.service
            state: started

